### PR TITLE
Implement orient3d + insphere

### PR DESCRIPTION
**Pull request by dmyyy**
Added tests + tests pass.

Would appreciate another pair of eyes on two_one_product implementation. (+ general changes since there's a lot and it's possible I missed something)

### CODE REVIEW

**Comment by urschrei** [comment]
Irrespective of reviews (I am doubtful that a human can meaningfully review the _robust_ code in general without immense effort) we should port over the tests from https://github.com/mourner/robust-predicates/blob/main/test/test.js and https://github.com/mourner/robust-predicates/tree/main/test/fixtures.

The latter is…some work and doesn't have to happen in this PR, but we should do it.

**Comment by rmanoka** [comment]
Thanks for the contribution @dmyyy ; thanks @urschrei for also porting the tests and ensuring correctness of this.  

At some point, we could add these predicates into the demo, so we can also get a visual feedback for the robustness.  It's built for 2-input predicate because the output is 2-d image, but I guess we can fix one input to just get a sense.

**Comment by urschrei** [comment]
Would anyone else like to review this? I'm happy to merge otherwise.

**Comment by michaelkirk** [comment]
It looks plausible, but as you said, it's tough to review the robust math meaningfully. Provided we also merge #24, this LGTM.

**Comment by frewsxcv** [comment]
> It looks plausible, but as you said, it's tough to review the robust math meaningfully. Provided we also merge #24, this LGTM.

Agreed with this. +1 to merge.

**Pull request merged**
